export const PageConstants = {
    enterKeyWord: `Enter `,
    selectKeyWord: `Select `,
    chooseKeyWord: `Choose `,
    maxLengthFifty: `Maximum of 50 characters`,
    maxDigitsFive: `Maximum of 5 digits`,
    maxDigitsTwenty: `Maximum of 20 digits`,
    projectName: `Project Name`,
    nameOfWorkPackage: `Name of Work Package`,
    typeOfWork: `Type of Work`,
    typeOfContract: `Type of Contract`,
    projectLocation: `Project Location`,
    contractDurationMonthsOrDays: `Contract Duration (Months or Days)`,
    contractDuration: `Contract Duration`,
    duration: `Duration`,
    lastDateOfTenderSubmission: `Last Date of Tender Submission`,
    budget: `Budget`,
    technicalBid: `Technical Bid`,
    financialBid: `Financial Bid`,
    technicalBidContractor: 'Upload Your Technical Bid',
    lastDateforSubmissionOfFilledPqDocument: `Last Date for Submission of filled PQ Document`,
    scheduledCompletion: `Scheduled Completion`,
    tentativeDateOfAwardOfWorks: `Tentative Date of Award of Works`,
    companyNameinFull: `Company Name in Full`,
    yearOfEstablishment: `Year of Establishment`,
    typeOfEstablishment: `Type of Establishment`,
    postalAddressCorporate: `Postal Address [Corporate Office]`,
    postalAddressLocal: `Postal Address [Local Office]`,
    telephone: `Telephone`,
    fax: `Fax`,
    contactPersonName: `Contact Person Name`,
    designation: `Designation`,
    mobileOrTel: `Mobile / Tel`,
    emailId: `Email ID`,
    nameOfRegionalHeadOrProjectCoordinator: `Name of Regional Head / Project Coordinator`,
    mobileNo: `Mobile No.`,
    preQualification: `The pre-qualification document shall be submitted in a sealed cover clearly indicating
        the Name of the project on top of the cover. Though soft copy form shall be accepted to
        expedite the process, the hard copy duly signed by contractor shall form the basis of
        final assessment. `,
    projectInformation: `The last date for receipt of completed pre-qualification documents with all the
        necessary certificates, is as specified in the initial section - 'Project Information'`,
    incomplete: `Incomplete or incorrect information provided herein by the agency shall result in
        automatic disqualification including cancellation of the order.`,
    time: `TIME shall be the essence of the contract.`,
    success: `Only the successful pre-qualified Contractors will be intimated for further.`,
    clientApplication: `Clients reserve the right to accept or reject any or all applications of
    pre-qualification without assigning any reasons thereof.`,
    noteInfo: `Please attach copies Certificates, Work orders, Project photographs, Company Profile etc
    in support of the information disclosed in this bid.`,
    listofthreeProjects: `List maximum 3 major projects executed.`,
    clientReference: `Client reserves the right to approach those named to seek a performance
    reference and rely on you having obtained the necessary consents.`,
    undertakingNote: `The information, facts, details etc disclosed in this document is true and
    correct. We take responsibility for the correctness of the same.`,
    saveBtn: `Draft`,
    submitBtn: `Submit`,
    updateBtn: `Update`,
    applyBtn: `Apply`,
    editBtn: `Edit`,
    viewBtn: `View`,
    viewApplicantsBtn: 'View Applicants',
    disabledMsgForTenderApplicant: 'Cannot apply for this tender as tender submission date is over',
    disabledWarningTenderApplicantMsg: 'Application form cannot be edited after submission',
    viewPQFormBtn: `View PQ`,
    editPQFormBtn: `Edit PQ`,
    createPQFormBtn: `Create PQ`,
    previousBtn: `Previous`,
    nextBtn: `Next`,
    addProjectBtn: `Add Project`,
    expandAllBtn: `Expand All`,
    collapseAllBtn: `Collapse All`,
    cancelBtn: `Cancel`,
    recommendBtn: 'Recommend',
    applyTenderMsg: `Are you sure you want to apply for this tender?`,
    submitTenderTitle: `Are you sure you want to submit the tender?`,
    submitTenderMsg: `Submitting this tender will disable further editing and will be sent to Admins for review`,
    submitPQFormTitle: `Are you sure you want to submit the PQ-Form?`,
    submitPQFormMsg: `Submitting will publish the tender and will be visible to contractors`,
    submitTenderApplicationTitle: `Submit your application for this tender?`,
    submitTenderApplicationMsg: `Submit action disables further editing of your application`,
    disabledWarningPQFormMsg: `Cannot edit the values because PQ-Form Published`,
    disabledWarningTenderMsg: `You cannot edit a tender when its in `,
    disableContractorBidMsg: 'You cannot edit tender bid is submitted',
    submitContractorBidTitle: 'Are you sure you want to submit the bid?',
    submitContractorBidMsg: 'Submitting this tender bid will disable further editing and will be sent to Admins for review',
    thankYouForReaching: 'Thank you for reaching out to us!',
    lookForward: 'We look forward to addressing your query.',
    category: 'Category',
    selectCategory: 'Select Category',
    name: 'Name',
    nameRequired: 'Name is required',
    minThreeChar: 'Minimum of 3 characters',
    maxFiftyChar: 'Maximum of 50 characters',
    emailRequired: 'Email ID is required',
    validEmail: 'Please enter valid email',
    mobileNumber: 'Mobile Number',
    requireMobilenumber: 'Mobile Number is required',
    validMobileNumber: 'Please enter valid mobile number',
    mobileTendDigits: 'Mobile number should be 10 digits',
    detailsOfQuery: 'Details of Query',
    detailsRequired: 'Details required',
    max250Char: 'Maximum of 250 characters',
    getInTouchh: 'Get in Touch!',
    getInTouch: 'Get in Touch',
    company: 'Company',
    contactUs: 'Contact Us',
    locateUs: 'Locate Us',
    aboutUs: 'About Us',
    inTheNews: 'In the News',
    pressInfo: 'Press Info',
    careers: 'Careers',
    termsPrivacy: 'Terms & Privacy',
    copyrightTrademark: 'Copyright & Trademark',
    mailOfc: 'gummadibuilt@gmail.com',
    address1Ofc: '8-2-293/82/A/471/1/3 F-2,',
    address2Ofc: 'Plot No 471, 2nd Floor,',
    address3Ofc: 'Road No 36, Jubilee Hills,',
    address4Ofc: 'Hyderabad - 500033.',
    phoneOfc: '+91 9988998800',
}