export const PageConstants = {
    enterKeyWord: `Enter `,
    selectKeyWord: `Select `,
    chooseKeyWord: `Choose `,
    maxLengthFifty: `Maximum of 50 characters`,
    maxDigitsFive: `Maximum of 5 digits`,
    maxDigitsTwenty: `Maximum of 20 digits`,
    projectName: `Project Name`,
    nameOfWorkPackage: `Name of Work Package`,
    typeOfWork: `Type of Work`,
    typeOfContract: `Type of Contract`,
    projectLocation: `Project Location`,
    contractDurationMonthsOrDays: `Contract Duration (Months or Days)`,
    contractDuration: `Contract Duration`,
    duration: `Duration`,
    lastDateOfTenderSubmission: `Last Date of Tender Submission`,
    budget: `Budget`,
    technicalBid: `Technical Bid`,
    financialBid: `Financial Bid`,
    technicalBidContractor: 'Upload Your Technical Bid',
    lastDateforSubmissionOfFilledPqDocument: `Last Date for Submission of filled PQ Document`,
    scheduledCompletion: `Scheduled Completion`,
    tentativeDateOfAwardOfWorks: `Tentative Date of Award of Works`,
    companyNameinFull: `Company Name in Full`,
    yearOfEstablishment: `Year of Establishment`,
    typeOfEstablishment: `Type of Establishment`,
    postalAddressCorporate: `Postal Address [Corporate Office]`,
    postalAddressLocal: `Postal Address [Local Office]`,
    telephone: `Telephone`,
    fax: `Fax`,
    contactPersonName: `Contact Person Name`,
    designation: `Designation`,
    mobileOrTel: `Mobile / Tel`,
    emailId: `Email ID`,
    nameOfRegionalHeadOrProjectCoordinator: `Name of Regional Head / Project Coordinator`,
    mobileNo: `Mobile No.`,
    preQualification: `The pre-qualification document shall be submitted in a sealed cover clearly indicating
        the Name of the project on top of the cover. Though soft copy form shall be accepted to
        expedite the process, the hard copy duly signed by contractor shall form the basis of
        final assessment. `,
    projectInformation: `The last date for receipt of completed pre-qualification documents with all the
        necessary certificates, is as specified in the initial section - 'Project Information'`,
    incomplete: `Incomplete or incorrect information provided herein by the agency shall result in
        automatic disqualification including cancellation of the order.`,
    time: `TIME shall be the essence of the contract.`,
    success: `Only the successful pre-qualified Contractors will be intimated for further.`,
    clientApplication: `Clients reserve the right to accept or reject any or all applications of
    pre-qualification without assigning any reasons thereof.`,
    noteInfo: `Please attach copies Certificates, Work orders, Project photographs, Company Profile etc
    in support of the information disclosed in this bid.`,
    listofthreeProjects: `List maximum 3 major projects executed.`,
    clientReference: `Client reserves the right to approach those named to seek a performance
    reference and rely on you having obtained the necessary consents.`,
    undertakingNote: `The information, facts, details etc disclosed in this document is true and
    correct. We take responsibility for the correctness of the same.`,
    saveBtn: `Draft`,
    submitBtn: `Submit`,
    updateBtn: `Update`,
    applyBtn: `Apply`,
    editBtn: `Edit`,
    viewBtn: `View`,
    viewApplicantsBtn: 'View Applicants',
    disabledMsgForTenderApplicant: 'Cannot apply for this tender as tender submission date is over',
    disabledWarningTenderApplicantMsg: 'Application form cannot be edited after submission',
    viewPQFormBtn: `View PQ`,
    editPQFormBtn: `Edit PQ`,
    createPQFormBtn: `Create PQ`,
    previousBtn: `Previous`,
    nextBtn: `Next`,
    addProjectBtn: `Add Project`,
    expandAllBtn: `Expand All`,
    collapseAllBtn: `Collapse All`,
    cancelBtn: `Cancel`,
    recommendBtn: 'Recommend',
    applyTenderMsg: `Are you sure you want to apply for this tender?`,
    submitTenderTitle: `Are you sure you want to submit the tender?`,
    submitTenderMsg: `Submitting this tender will disable further editing and will be sent to Admins for review`,
    submitPQFormTitle: `Are you sure you want to submit the PQ-Form?`,
    submitPQFormMsg: `Submitting will publish the tender and will be visible to contractors`,
    submitTenderApplicationTitle: `Submit your application for this tender?`,
    submitTenderApplicationMsg: `Submit action disables further editing of your application`,
    disabledWarningPQFormMsg: `Cannot edit the values because PQ-Form Published`,
    disabledWarningTenderMsg: `You cannot edit a tender when its in `,
    disableContractorBidMsg: 'You cannot edit tender bid is submitted',
    submitContractorBidTitle: 'Are you sure you want to submit the bid?',
    submitContractorBidMsg: 'Submitting this tender bid will disable further editing and will be sent to Admins for review',
    thankYouForReaching: 'Thank you for reaching out to us!',
    lookForward: 'We look forward to addressing your query.',
    category: 'Category',
    selectCategory: 'Select Category',
    name: 'Name',
    nameRequired: 'Name is required',
    minThreeChar: 'Minimum of 3 characters',
    maxFiftyChar: 'Maximum of 50 characters',
    emailRequired: 'Email ID is required',
    validEmail: 'Please enter valid email',
    mobileNumber: 'Mobile Number',
    requireMobilenumber: 'Mobile Number is required',
    validMobileNumber: 'Please enter valid mobile number',
    mobileTendDigits: 'Mobile number should be 10 digits',
    detailsOfQuery: 'Details of Query',
    detailsRequired: 'Details required',
    max250Char: 'Maximum of 250 characters',
    getInTouchh: 'Get in Touch!',
    getInTouch: 'Get in Touch',
    company: 'Company',
    contactUs: 'Contact Us',
    locateUs: 'Locate Us',
    aboutUs: 'About Us',
    inTheNews: 'In the News',
    pressInfo: 'Press Info',
    careers: 'Careers',
    termsPrivacy: 'Terms & Privacy',
    copyrightTrademark: 'Copyright & Trademark',
    mailOfc: 'gummadibuilt@gmail.com',
    address1Ofc: 'GummadiBuilt.com,',
    address2Ofc: '2d Floor, Above HDFC Bank,',
    address3Ofc: 'Road No.7, Banjara Hills,',
    address4Ofc: 'Hyderabad, Telangana 500082.',
    phoneOfc: '+91 9989077706',
    telOfc: '040 2340 5155',

    gummadiBuilt: 'Gummadi Built',
    titleMsg1: 'We Provide Clients with Resources To Build Their Dream Projects & Buildings',
    titleMsg2: '(A Platform To Bring Together Clients & Contractors/Vendors)',
    ourVision: 'Our Vision',
    ourVisionMsg: 'To become the most sought-after and reliable online platform for owners and contracting companies involved in the construction industry.',
    ourMission: 'Our Mission',
    ourMissionMsg: 'To provide an easily accessible online platform for all stakeholders involved in the construction industry, where they can achieve their business objectives, assisted and supported by highly experienced and qualified construction professionals, making the construction task a stress-free experience for them.',
    theProblem: 'The Problem',
    theProblemMsg: 'Construction projects in India are invariably delayed for multiple reasons. The major part of the blame goes to the executing agencies and material suppliers not being adequately resourceful, reliable, or not having the required quality standards as expected by the builder/client. Hence selection process of vendors and suppliers and closing contract agreements and purchase agreements, in ways favorable to the builder/project owner becomes the key aspect of every construction project.',
    solutionForClients: 'Gummadi Built Solution For Clients',
    solutionForClientsMsg: 'We make construction projects stress-free, using our expertise and skills in analyzing, shortlisting, and choosing from various Executing contractors and Vendors available in the market, best suited for the project, taking into account the nature and volume of works, site conditions, and the risks involved.',
    valueAddition: 'Gummadi Built Value Addition',
    valueAdditonMsg: 'We assure our customers, that we shall reduce the time and effort generally spent by them in the procurement process by at least 50%. Not to speak about the intangible benefits, Time being money!!! We assure our customers, that we shall provide alternate resources in case of any delay in the project due to reasons attributable to the selected vendor/supplier, without affecting the progress of works, in a legally valid manner, within the purview of the agreements.',
    solutionForContractors: 'Gummadi Built Solution For Contractors, Suppliers & Vendors',
    solutionForContractorsMsg: 'We provide access to a common platform for Contracting Companies doing business in all trades of construction contracts and supplying construction materials and supplies. We make sure they are entering into a robust and credible contract agreement, whereby their business and revenue are safeguarded by agreements drafted by qualified and experienced professionals.',
    btnRegisterAsClient: 'Register As Client/Builder',
    btnRegisterAsIndividual: 'Register As Indiviadual Building Owner',
    btnRegisterAsContractor: 'Register As Contractor',
    btnRegisterAsMaterialSupplier: 'Register As Material Supplier',
    aboutUsMsg: 'Gummadi Built is a start-up established in the year 2023, by a team of construction professionals carrying more than 30 years of experience in Project Management, Procurement Management, and Contracts Administration of Large, Medium, and Small scale projects in all sectors and trades of construction, such as Housing, Commercial, Industrial and Infrastructure industries.',
    ourValues: 'Our Values',
    ourValuesMsg: 'We believe that the personal commitment, earnestness, integrity, and professionalism of parties involved in a contract, would make the Construction of Projects, a stress-free experience.',
    services: 'Services',
    servicesMsg1: 'The Chart below shows a typical step-by-step process involved in using this platform by our registered customers. The Scope and Methodology of our services and deliverables thereof have also been indicated. The scope and methodology shall be customized to suit specific customer requirements.',
    servicesMsg2: 'Gummadi Built shall facilitate the signing of the Main Construction Contract Agreement between the Client and Contractor/Vendor, without being a party to the contract. Gummadi Built shall have separate service contract agreements executed with the client and contractor, obligating each party of their responsibilities in providing and availing the services through Gummadi Built Web Portal.',
    buttonPayment: 'Payment',
    paymentSendto: 'Send Payment to:',
    financialRadioErrorMsg: 'Please choose an option for Financial bid.',

    earthWorkCutting: 'Earthwork Cutting & Filling Contractors - Find the Best Fit for Your Project',
    earthWorkCuttingDescription1: "When it comes to construction projects, one of the most important aspects is earthwork cutting and filling. This involves the excavation and movement of large amounts of soil, rocks, and other materials to prepare the site for construction. It's a critical task that requires the right equipment and expertise to ensure that the project is completed safely and efficiently.",
    earthWorkCuttingDescription2: "At Gummadi Built, we understand the importance of finding the right contractor for your earthwork cutting and filling needs. That's why we have a huge list of contractors specifically dedicated to this area of expertise. Our team works with a network of highly skilled contractors to ensure that we can provide our clients with the best options available.",
    earthWorkCuttingSubHeading1: "Refining Contractor Profiles to Find the Best Fit",
    earthWorkCuttingSubHeading1Description: "Our process begins with understanding the specific requirements of your project. By providing us with the details of your earthwork cutting and filling needs, we can then analyse your project and develop a list of potential contractors that are a good fit. We will then refine this list further based on factors such as:",
    earthWorkCuttingSubHeading1List1: "Experience in earthwork cutting and filling projects",
    earthWorkCuttingSubHeading1List2: "Availability to work within your timeline",
    earthWorkCuttingSubHeading1List3: "Equipment and technology capabilities",
    earthWorkCuttingSubHeading1List4: "Reputation for quality workmanship and safety standards",
    earthWorkCuttingSubHeading2: "Pricing and budget considerations",
    earthWorkCuttingSubHeading2Description: "Once we've identified the most suitable contractors, we'll present you with a shortlist of options to choose from. From there, you can select the contractor that best meets your needs and budget.",
    earthWorkCuttingSubHeading3: "Trust and Transparency",
    earthWorkCuttingSubHeading3Description1: "At Gummadi Built, we believe in building trust and transparency with our clients. That's why we provide detailed information about each contractor, including their portfolio, experience, and certifications. We also encourage our clients to provide feedback on their experience working with our contractors, which helps us to continually refine and improve our services.",
    earthWorkCuttingSubHeading3Description2: "If you're in need of earthwork cutting and filling contractors, Gummadi Built can help you find the best fit for your project. With our extensive network of contractors and our commitment to quality and transparency, you can trust that we'll help you get the job done right.",


    projectDesign: 'Project Design & Engineering Consultancy Services',
    projectDesignDescription: "At Gummadi Built, we understand that every construction project is unique and comes with its own set of challenges.",
    projectDesignSubHeading1: "What are Project Consultancy Services?",
    projectDesignSubHeading1Description: "At Gummadi Built, we have experienced and knowledgeable project consultants listed, who can help you  in every aspect of construction projects, from initial planning and design to project management and implementation. List of services:",
    projectDesignSubHeading1List1: "Architectural Design Consultancy",
    projectDesignSubHeading1List2: "Structural Design COnsultancy",
    projectDesignSubHeading1List3: "Interior Design Consultancy",
    projectDesignSubHeading1List4: "Electrical Engineering Consultancy (HT/LT/LV/ELV Systems)",
    projectDesignSubHeading1List5: "Mechanical Engineering Consultancy (Fire Fighting Systems, Fire Protection, Detection and Alarm Systems, Plumbing, Sanitary and Public Health Engineering Services)",
    projectDesignSubHeading1List6: "Specialised Building Engineering Services and Management Systems (Security Systems, Data & Communication Systems, Audio Video Systems, Building Automation Systems, Integrated Building Management Systems, Facility Management Systems, Operational Management Systems)",
    projectDesignSubHeading1List7: "Landscape Design Consultancy",
    projectDesignSubHeading1List8: "Lighting Consultancy ",
    projectDesignSubHeading1List9: "Traffic Analysis and Engineering Consultancy",
    projectDesignSubHeading1List10: "Facade Consultancy",
    projectDesignSubHeading1List11: "Lift & Elevators Consultants",
    projectDesignSubHeading2: "How Gummadi Built Refines the consultant Profiles for You",
    projectDesignSubHeading2Description: "Our process for refining consultant profiles involves:",
    projectDesignSubHeading2Lis1: "Understanding the project requirements: We start by understanding the specific needs of our clients' construction projects. This includes the scope, budget, timeline, and other requirements.",
    projectDesignSubHeading2Lis2: "Shortlisting the best contractors: We then analyze our database of contractors to identify those who are best suited to meet our clients' project requirements. We consider factors such as the contractor's expertise, experience, and portfolio.",
    projectDesignSubHeading2Lis3: "Presenting the shortlisted contractors to the client: We present the shortlisted contractors to the client for review and selection. We provide detailed profiles of each contractor, including their experience, expertise, and portfolio.",
    projectDesignSubHeading2Lis4: "Monitoring contractor performance: Once the contractor is selected, we monitor their performance throughout the project to ensure that they meet the project requirements and deadlines.",
    projectDesignSubHeading3: "Get in Touch with Us",
    projectDesignSubHeading3Description: "If you're looking for project consultancy services for your construction project, look no further than Gummadi Built. Contact us today to learn more about our services and how we can help you achieve your construction goals.",

    landSurveying: "Land Surveying Services",
    landSurveyingDescription: "Land surveying is the process of measuring and mapping the physical features of a piece of land. It is an essential service for a variety of industries, including construction, engineering, real estate, and land development. At Gummadi Built, we understand the importance of accurate land surveying, which is why we offer a wide range of land surveying services to our clients.",
    landSurveyingSubHeading1: "What is Land Surveying?",
    landSurveyingSubHeading1Description: "Land surveying involves the use of advanced technology and equipment to measure and map out the physical features of a piece of land. These features can include boundaries, elevations, contours, and the locations of buildings, roads, and other structures. The information gathered during a land survey is used to create detailed maps and plans that can be used in a variety of industries, including construction, engineering, and land development.",
    landSurveyingSubHeading2: "Services by Land Surveyors.",
    landSurveyingSubHeading2Description: "At Gummadi Built, we offer a comprehensive range of land surveying services to our clients. Our team of experienced land surveyors uses the latest technology and equipment to provide accurate and reliable surveying services. Our land surveying services include:",
    landSurveyingSubHeading2List1: "Topographic Survey",
    landSurveyingSubHeading2List1Description: "A topographic survey is used to measure and map out the physical features of a piece of land. This can include the locations of buildings, roads, and other structures, as well as elevations, contours, and other features of the land.",
    landSurveyingSubHeading2List2: "Boundary Survey",
    landSurveyingSubHeading2List2Description: "A boundary survey is used to determine the exact boundaries of a piece of land. This can include the locations of fences, walls, and other structures that mark the boundaries of the property.",
    landSurveyingSubHeading2List3: "Construction Survey",
    landSurveyingSubHeading2List3Description: "A construction survey is used to provide accurate measurements and mapping of a construction site. This can include the locations of buildings, roads, and other structures, as well as the elevations and contours of the land.",
    landSurveyingSubHeading2List4: "Site Plan Survey",
    landSurveyingSubHeading2List4Description: "A site plan survey is used to provide a detailed map of a construction site or land development project. This can include the locations of buildings, roads, and other structures, as well as elevations, contours, and other features of the land.",
    landSurveyingSubHeading3: "Why Choose Gummadi Built for Land Surveying Services?",
    landSurveyingSubHeading3Description1: "At Gummadi Built, we are committed to providing our clients with the highest quality land surveyors. Experienced land surveyors uses the latest technology and equipment to provide accurate and reliable surveying services. We work closely with our clients to understand their specific needs and requirements, and we are committed to delivering results that exceed their expectations.",
    landSurveyingSubHeading3Description2: "Whether you are in the construction, engineering, real estate, or land development industry, Gummadi Built can provide you the land surveyors you need. Contact us today to learn more about our services and how we can help you with your land surveying needs.",

    geoTechnical: "Geotechnical Investigation Consultants: Analysing Soil and Rock Conditions for Safe Construction",
    geoTechnicalDescription: "Geotechnical investigation is an essential aspect of any construction project. It involves analysing the soil, rock, and groundwater conditions at a construction site to ensure safe and cost-effective construction. At Gummadi Built, we provide access to the best geotechnical investigation consultants in the industry.",
    geoTechnicalSubHeading1: "Why Geotechnical Investigation is Important for Construction Projects",
    geoTechnicalSubHeading1Description: "A thorough geotechnical investigation can help identify potential problems such as soil instability, soil liquefaction, landslides, and sinkholes, among others. This information can help engineers design a safe and cost-effective foundation and support system for the construction project.",
    geoTechnicalSubHeading2: "Types of Geotechnical Investigation Services Offered by Gummadi Built",
    geoTechnicalSubHeading2Description: "Our geotechnical investigation consultants offer a range of services, including:",
    geoTechnicalSubHeading2List: [{ name: "Soil and Rock Testing: ", description: "Testing the strength and characteristics of soil and rock samples to determine their suitability for construction." },
    { name: "Geophysical Surveys: ", description: "Using geophysical techniques to study subsurface soil and rock conditions to identify potential hazards." },
    { name: "Groundwater Studies: ", description: "Investigating the groundwater table and flow characteristics to ensure safe and stable construction." },
    { name: "Slope Stability Analysis: ", description: "Evaluating the stability of slopes and embankments to prevent landslides and ensure safe construction." },],
    geoTechnicalSubHeading3: "How Gummadi Built Refines the Consultant's Profiles for You",
    geoTechnicalSubHeading3Description1: "At Gummadi Built, we understand that every construction project has unique requirements. That's why we analyse the project details and shortlist the best geotechnical investigation consultants based on their experience, expertise, and reliability. Our team of experts conducts a thorough background check to ensure that our clients get access to the most reliable and competent consultants.",
    geoTechnicalSubHeading3Description2: "Geotechnical investigation is a critical aspect of any construction project. By providing access to the best geotechnical investigation consultants in the industry, Gummadi Built ensures that your construction project is safe and cost-effective. Contact us today to know more about our geotechnical investigation services.",

    buildingStrengthening: "Building Strengthening & Rehabilitation Works",
    buildingStrengtheningDescription: "Building Strengthening & Rehabilitation Works are essential to ensure the safety, durability, and functionality of existing structures. At Gummadibuilt, we provide a comprehensive platform that connects clients with a diverse range of experienced contractors specializing in building strengthening and rehabilitation. Whether you need to address structural deficiencies, perform seismic upgrades, or restore and renovate aging buildings, our network of contractors offers tailored solutions to meet your specific requirements.",
    buildingStrengtheningSubHeading1: "Services Offered by the contractors",
    buildingStrengtheningSubHeading1Description: "Our network of contractors offers a wide array of services for building strengthening and rehabilitation projects, including:",
    buildingStrengtheningSubHeading1List: [{ name: "Structural Assessment: ", description: "Thorough evaluation and analysis of the existing building structure to identify weaknesses, defects, and areas that require strengthening or repairs." },
    { name: "Structural Upgrades: ", description: "Implementing measures to improve the structural integrity of the building, such as reinforcing beams, columns, and foundations, and installing additional support systems." },
    { name: "Seismic Retrofitting: ", description: "Strengthening buildings to enhance their resistance to earthquakes and other seismic events, including the installation of seismic dampers, bracing, and structural enhancements." },
    { name: "Façade Restoration: ", description: "Restoring and renovating the exterior façade of buildings to enhance aesthetics, weatherproofing, and historical preservation." },
    { name: "MEP Upgrades: ", description: "Upgrading mechanical, electrical, and plumbing systems to meet modern standards, improve energy efficiency, and ensure optimal functionality." },
    { name: "Historical Building Rehabilitation: ", description: "Preserving and rehabilitating historical structures while maintaining their architectural significance and cultural heritage." },
    { name: "Renovation and Space Optimization: ", description: "Transforming existing spaces to maximize their potential and meet evolving functional requirements." }],
    buildingStrengtheningSubHeading2: "Connect with Gummadi Built",
    buildingStrengtheningSubHeading2Description1: "Are you planning a building strengthening or rehabilitation project? Gummadibuilt is here to assist you in finding the right contractor. By partnering with our network of experienced professionals, you can ensure the success of your project.",
    buildingStrengtheningSubHeading2Description2: "To get started contact Gummadi Built and get the shortlisted contractors list for your project, browse through the list of contractors specializing in Building Strengthening & Rehabilitation Works and explore their profiles to find the best fit for your project requirements. Connect with the contractors directly to discuss your project details, receive quotes, and make informed decisions.",

    qualityTesting: "Quality Testing of Materials & Works",
    qualityTestingDescription: "Quality Testing of Materials & Works is a crucial aspect of any construction project to ensure compliance with industry standards and regulations. At Gummadibuilt, we provide a platform that connects clients with experienced certified agencies specializing in quality testing services. Whether you need to verify the quality of construction materials or assess the workmanship of ongoing projects, our network of certified agencies offers comprehensive testing solutions to ensure the highest standards of quality and performance.",
    qualityTestingSubHeading: "Services Offered by the contractors",
    qualityTestingSubHeadingDescription: "Our network of contractors offers a wide range of quality testing services for materials and works, including:",
    qualityTestingSubHeadingList: [{ name: "Material Testing: ", description: "Comprehensive testing of construction materials such as concrete, steel, aggregates, soil, asphalt, and more to assess their strength, durability, composition, and adherence to specifications." },
    { name: "Workmanship Assessment: ", description: "Evaluation of construction works, including structural elements, finishes, electrical and plumbing systems, to ensure compliance with design requirements, safety standards, and workmanship quality." },
    { name: "Non-Destructive Testing: ", description: "Utilization of non-destructive testing techniques such as ultrasonic testing, radiographic testing, thermal imaging, and more to assess the integrity and performance of structures and materials without causing damage." },
    { name: "Quality Control Inspections: ", description: "Regular on-site inspections to monitor the quality of construction activities, identify deviations from standards, and provide timely feedback for corrective actions." },
    { name: "Laboratory Testing: ", description: "Analysis of samples in accredited laboratories to assess properties such as material strength, composition, permeability, compaction, and other parameters as per relevant testing standards." },
    { name: "Documentation and Reporting: ", description: "Detailed documentation of test results, including comprehensive reports, data analysis, and recommendations for improvement or corrective measures." }],
    qualityTestingDescription2: "Our network of contractors specializing in quality testing brings extensive expertise and state-of-the-art equipment to deliver accurate and reliable results.",
    qualityTestingDescription3: "To find the right contractor for your quality testing requirements, connect with Gummadibuilt and get the list of expert contractors for your project. Explore their profiles to learn more about their expertise, certifications, and past projects. Connect with the contractors directly to discuss your specific needs and project details.",

    nonDestructiveTesting: "Non-Destructive Testing",
    nonDestructiveTestingDescription: "Non-Destructive Testing (NDT) plays a vital role in ensuring the integrity, reliability, and safety of structures and materials without causing damage. At Gummadibuilt, we connect clients with experienced licensed agencies specializing in non-destructive testing services. Our network of licensed agencies utilizes advanced techniques and equipment to assess the condition, quality, and performance of various materials and structures.",
    nonDestructiveTestingSubHeading: "Services Offered in Non-Desctructive Testing",
    nonDestructiveTestingSubHeadingDescription: "Our network of contractors offers a wide range of non-destructive testing services, including:",
    nonDestructiveTestingSubHeadingList: [{ name: "Ultrasonic Testing: ", description: "Using high-frequency sound waves to detect defects, thickness measurements, and evaluate the integrity of materials such as metals, concrete, composites, and more." },
    { name: "Radiographic Testing: ", description: "Utilizing X-rays or gamma rays to examine internal structures and detect flaws, cracks, or defects in welds, castings, and other components." },
    { name: "Magnetic Particle Testing: ", description: "Detecting surface and near-surface defects in ferromagnetic materials using magnetic fields and magnetic particles." },
    { name: "Liquid Penetrant Testing: ", description: "Identifying surface-breaking defects and discontinuities in non-porous materials by applying a liquid penetrant and observing its penetration into flaws." },
    { name: "Visual Inspection: ", description: "Conducting visual examinations to identify visible defects, surface irregularities, corrosion, and other anomalies." },
    { name: "Thermal Imaging: ", description: "Using infrared technology to detect thermal patterns, identify heat loss, moisture intrusion, and electrical faults in structures." },
    { name: "Eddy Current Testing: ", description: "Evaluating the conductivity, thickness, and integrity of conductive materials by inducing electrical currents and measuring the resulting electromagnetic fields." }
    ],
    nonDestructiveTestingDescription2: "If you require non-destructive testing services for your construction projects, Gummadibuilt is here to assist you. Our network of experienced contractors specializing in NDT techniques can ensure the integrity and reliability of your structures and materials.",
    nonDestructiveTestingDescription3: "To find the right contractor for your non-destructive testing needs, connect with Gummadibuilt and get the list of eligible contractors for your need. Explore their profiles to learn more about their expertise, certifications, and past projects. Connect with the contractors directly to discuss your specific requirements and project details.",
    nonDestructiveTestingDescription4: "Choose Gummadibuilt for reliable and accurate non-destructive testing solutions to ensure the safety and quality of your construction projects.",

    pileFoundations: "Pile Foundations",
    pileFoundationsDescription: "Pile foundations are essential structural elements used to transfer building loads to deeper, more stable soil layers. At Gummadibuilt, we connect clients with experienced contractors specializing in pile foundation construction. Our network of contractors possesses the expertise and equipment required to design and install pile foundations for a wide range of projects, ensuring stability, durability, and structural integrity.",
    pileFoundationsSubHeading: "Services Offered by the Pile Foundation consultants",
    pileFoundationsSubHeadingDescription: "Our network of contractors offers a comprehensive range of pile foundation services, including:",
    pileFoundationsSubHeadingList: [
        { name: "Pile Design: ", description: "Utilizing geotechnical data and engineering analysis to design appropriate pile foundations based on project requirements, soil conditions, and structural considerations." },
        { name: "Pile Installation: ", description: "Executing efficient and accurate pile installation using various techniques such as driven piles, auger-cast piles, drilled shafts, micropiles, and helical piles." },
        { name: "Load Testing: ", description: "Conducting load tests on pile foundations to determine their load-bearing capacity, evaluate performance, and ensure compliance with design specifications." },
        { name: "Pile Integrity Testing: ", description: "Performing integrity tests to assess the condition and integrity of piles, identify any potential defects or damage, and ensure their suitability for the intended purpose." },
        { name: "Foundation Rehabilitation: ", description: "Providing rehabilitation solutions for existing pile foundations, including strengthening, repairs, and underpinning to address issues such as settlement, deterioration, or changes in load conditions." },
    ],
    pileFoundationsSubHeading2: "Take the Next Step",
    pileFoundationsSubHeading2Description1: "If you require pile foundation services for your construction project, Gummadibuilt is here to assist you. Connect with us to get access to a network of experienced contractors specializing in pile foundations.",
    pileFoundationsSubHeading2Description2: "To find the right contractor for your pile foundation needs, connect with Gummadibuilt and get the list of eligible contractors for your project. Explore their profiles to learn more about their expertise, certifications, and past projects. Connect with the contractors directly to discuss your specific requirements and project details.",
    pileFoundationsSubHeading2Description3: "Choose Gummadibuilt for reliable and efficient pile foundation solutions that ensure the stability and long-term performance of your structures.",

    dewateringSystems: "Dewatering Systems",
    dewateringSystemsDescription: "Dewatering systems play a crucial role in construction projects by removing groundwater or excess water from construction sites, excavations, and basements. At Gummadibuilt, we connect clients with experienced contractors specializing in dewatering systems. Our network of contractors offers innovative and efficient solutions to manage water levels and ensure a safe and stable construction environment.",
    dewateringSystemsSubHeading: "Services Offered by Dewatering systems contractors",
    dewateringSystemsSubHeadingDescription: "Our network of contractors provides a wide range of dewatering system services, including:",
    dewateringSystemsSubHeadingList: [
        { name: "Wellpoint Dewatering: ", description: "Installing wellpoints and utilizing vacuum pumps to lower groundwater levels in shallow excavations and construction sites." },
        { name: "Deep Well Dewatering: ", description: "Utilizing deep wells and submersible pumps to handle high water table conditions and control water flow in deeper excavations or basements." },
        { name: "Sump Pump Systems: ", description: "Installing sump pumps to collect and discharge water from basements, underground structures, or areas prone to water accumulation." },
        { name: "Horizontal Well Dewatering: ", description: "Implementing horizontal well systems to effectively control and redirect groundwater flow in specific directions." },
        { name: "Open Excavation Dewatering: ", description: "Designing and implementing drainage systems to manage and control water levels in open excavations during construction." },
        { name: "Temporary Bypass Pumping: ", description: "Providing temporary pumping solutions to redirect water flow, manage water levels, or support construction activities during dewatering operations." },
        { name: "Water Treatment: ", description: "Offering water treatment solutions to ensure compliance with environmental regulations and discharge water safely." }
    ],
    dewateringSystemsSubHeading2: "Connect with us",
    dewateringSystemsSubHeading2Description1: "If you require dewatering system services for your construction project, Gummadibuilt is here to assist you. Connect with us to get access to a network of experienced contractors specializing in dewatering systems.",
    dewateringSystemsSubHeading2Description2: "To find the right contractor for your dewatering system needs, connect with Gummadibuilt and get the list of eligible contractors for your project.",
    dewateringSystemsSubHeading2Description3: "Explore their profiles to learn more about their expertise, certifications, and past projects. Connect with the contractors directly to discuss your specific requirements and project details.",
    dewateringSystemsSubHeading2Description4: "Choose Gummadibuilt for reliable and efficient dewatering system solutions that ensure a well-controlled construction environment.",
}