export const PageConstants = {
    enterKeyWord: `Enter `,
    selectKeyWord: `Select `,
    chooseKeyWord: `Choose `,
    maxLengthFifty: `Maximum of 50 characters`,
    maxDigitsFive: `Maximum of 5 digits`,
    maxDigitsTwenty: `Maximum of 20 digits`,
    projectName: `Project Name`,
    nameOfWorkPackage: `Name of Work Package`,
    typeOfWork: `Type of Work`,
    typeOfContract: `Type of Contract`,
    projectLocation: `Project Location`,
    contractDurationMonthsOrDays: `Contract Duration (Months or Days)`,
    contractDuration: `Contract Duration`,
    duration: `Duration`,
    lastDateOfTenderSubmission: `Last Date of Tender Submission`,
    budget: `Budget`,
    technicalBid: `Technical Bid`,
    financialBid: `Financial Bid`,
    technicalBidContractor: 'Upload Your Technical Bid',
    lastDateforSubmissionOfFilledPqDocument: `Last Date for Submission of filled PQ Document`,
    scheduledCompletion: `Scheduled Completion`,
    tentativeDateOfAwardOfWorks: `Tentative Date of Award of Works`,
    companyNameinFull: `Company Name in Full`,
    yearOfEstablishment: `Year of Establishment`,
    typeOfEstablishment: `Type of Establishment`,
    postalAddressCorporate: `Postal Address [Corporate Office]`,
    postalAddressLocal: `Postal Address [Local Office]`,
    telephone: `Telephone`,
    fax: `Fax`,
    contactPersonName: `Contact Person Name`,
    designation: `Designation`,
    mobileOrTel: `Mobile / Tel`,
    emailId: `Email ID`,
    nameOfRegionalHeadOrProjectCoordinator: `Name of Regional Head / Project Coordinator`,
    mobileNo: `Mobile No.`,
    preQualification: `The pre-qualification document shall be submitted in a sealed cover clearly indicating
        the Name of the project on top of the cover. Though soft copy form shall be accepted to
        expedite the process, the hard copy duly signed by contractor shall form the basis of
        final assessment. `,
    projectInformation: `The last date for receipt of completed pre-qualification documents with all the
        necessary certificates, is as specified in the initial section - 'Project Information'`,
    incomplete: `Incomplete or incorrect information provided herein by the agency shall result in
        automatic disqualification including cancellation of the order.`,
    time: `TIME shall be the essence of the contract.`,
    success: `Only the successful pre-qualified Contractors will be intimated for further.`,
    clientApplication: `Clients reserve the right to accept or reject any or all applications of
    pre-qualification without assigning any reasons thereof.`,
    noteInfo: `Please attach copies Certificates, Work orders, Project photographs, Company Profile etc
    in support of the information disclosed in this bid.`,
    listofthreeProjects: `List maximum 3 major projects executed.`,
    clientReference: `Client reserves the right to approach those named to seek a performance
    reference and rely on you having obtained the necessary consents.`,
    undertakingNote: `The information, facts, details etc disclosed in this document is true and
    correct. We take responsibility for the correctness of the same.`,
    saveBtn: `Draft`,
    submitBtn: `Submit`,
    updateBtn: `Update`,
    applyBtn: `Apply`,
    editBtn: `Edit`,
    viewBtn: `View`,
    viewApplicantsBtn: 'View Applicants',
    disabledMsgForTenderApplicant: 'Cannot apply for this tender as tender submission date is over',
    disabledWarningTenderApplicantMsg: 'Application form cannot be edited after submission',
    viewPQFormBtn: `View PQ`,
    editPQFormBtn: `Edit PQ`,
    createPQFormBtn: `Create PQ`,
    previousBtn: `Previous`,
    nextBtn: `Next`,
    addProjectBtn: `Add Project`,
    expandAllBtn: `Expand All`,
    collapseAllBtn: `Collapse All`,
    cancelBtn: `Cancel`,
    recommendBtn: 'Recommend',
    applyTenderMsg: `Are you sure you want to apply for this tender?`,
    submitTenderTitle: `Are you sure you want to submit the tender?`,
    submitTenderMsg: `Submitting this tender will disable further editing and will be sent to Admins for review`,
    submitPQFormTitle: `Are you sure you want to submit the PQ-Form?`,
    submitPQFormMsg: `Submitting will publish the tender and will be visible to contractors`,
    submitTenderApplicationTitle: `Submit your application for this tender?`,
    submitTenderApplicationMsg: `Submit action disables further editing of your application`,
    disabledWarningPQFormMsg: `Cannot edit the values because PQ-Form Published`,
    disabledWarningTenderMsg: `You cannot edit a tender when its in `,
    disableContractorBidMsg: 'You cannot edit tender bid is submitted',
    submitContractorBidTitle: 'Are you sure you want to submit the bid?',
    submitContractorBidMsg: 'Submitting this tender bid will disable further editing and will be sent to Admins for review',
    thankYouForReaching: 'Thank you for reaching out to us!',
    lookForward: 'We look forward to addressing your query.',
    category: 'Category',
    selectCategory: 'Select Category',
    name: 'Name',
    nameRequired: 'Name is required',
    minThreeChar: 'Minimum of 3 characters',
    maxFiftyChar: 'Maximum of 50 characters',
    emailRequired: 'Email ID is required',
    validEmail: 'Please enter valid email',
    mobileNumber: 'Mobile Number',
    requireMobilenumber: 'Mobile Number is required',
    validMobileNumber: 'Please enter valid mobile number',
    mobileTendDigits: 'Mobile number should be 10 digits',
    detailsOfQuery: 'Details of Query',
    detailsRequired: 'Details required',
    max250Char: 'Maximum of 250 characters',
    getInTouchh: 'Get in Touch!',
    getInTouch: 'Get in Touch',
    company: 'Company',
    contactUs: 'Contact Us',
    locateUs: 'Locate Us',
    aboutUs: 'About Us',
    inTheNews: 'In the News',
    pressInfo: 'Press Info',
    careers: 'Careers',
    termsPrivacy: 'Terms & Privacy',
    copyrightTrademark: 'Copyright & Trademark',
    mailOfc: 'gummadibuilt@gmail.com',
    address1Ofc: 'GummadiBuilt.com,',
    address2Ofc: '2d Floor, Above HDFC Bank,',
    address3Ofc: 'Road No.7, Banjara Hills,',
    address4Ofc: 'Hyderabad, Telangana 500082.',
    phoneOfc: '+91 9989077706',
    telOfc: '040 2340 5155',

    gummadiBuilt: 'Gummadi Built',
    titleMsg1: 'We Provide Clients with Resources To Build Their Dream Projects & Buildings',
    titleMsg2: '(A Platform To Bring Together Clients & Contractors/Vendors)',
    ourVision: 'Our Vision',
    ourVisionMsg: 'To become the most sought-after and reliable online platform for owners and contracting companies involved in the construction industry.',
    ourMission: 'Our Mission',
    ourMissionMsg: 'To provide an easily accessible online platform for all stakeholders involved in the construction industry, where they can achieve their business objectives, assisted and supported by highly experienced and qualified construction professionals, making the construction task a stress-free experience for them.',
    theProblem: 'The Problem',
    theProblemMsg: 'Construction projects in India are invariably delayed for multiple reasons. The major part of the blame goes to the executing agencies and material suppliers not being adequately resourceful, reliable, or not having the required quality standards as expected by the builder/client. Hence selection process of vendors and suppliers and closing contract agreements and purchase agreements, in ways favorable to the builder/project owner becomes the key aspect of every construction project.',
    solutionForClients: 'Gummadi Built Solution For Clients',
    solutionForClientsMsg: 'We make construction projects stress-free, using our expertise and skills in analyzing, shortlisting, and choosing from various Executing contractors and Vendors available in the market, best suited for the project, taking into account the nature and volume of works, site conditions, and the risks involved.',
    valueAddition: 'Gummadi Built Value Addition',
    valueAdditonMsg: 'We assure our customers, that we shall reduce the time and effort generally spent by them in the procurement process by at least 50%. Not to speak about the intangible benefits, Time being money!!! We assure our customers, that we shall provide alternate resources in case of any delay in the project due to reasons attributable to the selected vendor/supplier, without affecting the progress of works, in a legally valid manner, within the purview of the agreements.',
    solutionForContractors: 'Gummadi Built Solution For Contractors, Suppliers & Vendors',
    solutionForContractorsMsg: 'We provide access to a common platform for Contracting Companies doing business in all trades of construction contracts and supplying construction materials and supplies. We make sure they are entering into a robust and credible contract agreement, whereby their business and revenue are safeguarded by agreements drafted by qualified and experienced professionals.',
    btnRegisterAsClient: 'Register As Client/Builder',
    btnRegisterAsIndividual: 'Register As Indiviadual Building Owner',
    btnRegisterAsContractor: 'Register As Contractor',
    btnRegisterAsMaterialSupplier: 'Register As Material Supplier',
    aboutUsMsg: 'Gummadi Built is a start-up established in the year 2023, by a team of construction professionals carrying more than 30 years of experience in Project Management, Procurement Management, and Contracts Administration of Large, Medium, and Small scale projects in all sectors and trades of construction, such as Housing, Commercial, Industrial and Infrastructure industries.',
    ourValues: 'Our Values',
    ourValuesMsg: 'We believe that the personal commitment, earnestness, integrity, and professionalism of parties involved in a contract, would make the Construction of Projects, a stress-free experience.',
    services: 'Services',
    servicesMsg1: 'The Chart below shows a typical step-by-step process involved in using this platform by our registered customers. The Scope and Methodology of our services and deliverables thereof have also been indicated. The scope and methodology shall be customized to suit specific customer requirements.',
    servicesMsg2: 'Gummadi Built shall facilitate the signing of the Main Construction Contract Agreement between the Client and Contractor/Vendor, without being a party to the contract. Gummadi Built shall have separate service contract agreements executed with the client and contractor, obligating each party of their responsibilities in providing and availing the services through Gummadi Built Web Portal.',
}