name: release
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install dependencies 
      run: npm install --legacy-peer-deps
   
    - name: Momentarily remove pull request review protection
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        unprotect_reviews: true 

    - name: Run Semantic Release
      run: npx semantic-release
